### ISSUE TITLE
My run start issue  

### ISSUE THREAD

**Issue by tontheonelove** [zyairelai/futures-hero#18]
Hi  Sir.   

         i fork  and  follow tutorial step 
         
       1.   add  my key & secrete  in  binance_futures_api.py 
       2.   run pip3 install apscheduler==3.6.3
                   pip3 install cryptography==3.3.2 
                   pip3 install python-binance==0.7.9
                   pip3 install termcolor==1.1.0
       3.   try run  python3 run.py

but not work    and see error  like this

root@ubuntu:~/futures-hero# python3 run.py
Pair Name        :   BTCUSDT
Trade Quantity   :   0.001 BTC
Leverage         :   50

===========================================
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    import strategy_hybrid
  File "/root/futures-hero/strategy_hybrid.py", line 1, in <module>
    import RSI
  File "/root/futures-hero/RSI.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
root@ubuntu:~/futures-hero# pandas -v
pandas: command not found
===========================================

**Comment by tontheonelove** [comment]
Thankyou for help me sir.       i follow   pip3 install -r requirements.txt   

and i try run  python3 run.py    again    is still issue  i dont know why   pls help again





root@ubuntu:~/futures-hero# python3 run.py
Pair Name        :   BTCUSDT
Trade Quantity   :   0.001 BTC
Leverage         :   50

Traceback (most recent call last):
  File "run.py", line 7, in <module>
    import strategy_hybrid
  File "/root/futures-hero/strategy_hybrid.py", line 1, in <module>
    import RSI
  File "/root/futures-hero/RSI.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
